MyTube/MyTube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include(('app.urls', 'app'), namespace='app')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('studio/', include(('studio.urls', 'studio'), namespace='studio')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyTube/app/urls.py
from django . urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('video/<int:pk>', views.video, name='video'),
    path('likes/<int:pk>', views.likes, name='likes'),
    path('dislikes/<int:pk>', views.dislikes, name='dislikes'),
    path('comment_likes/<int:pk>', views.comment_likes, name='comment_likes'),
    path('comment_dislikes/<int:pk>', views.comment_dislikes, name='comment_dislikes'),
    path('reply/<int:pk>', views.reply, name='reply'),

]

MyTube/studio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('video_create/', views.video_create, name='video_create'),
    path('video_edit/<int:pk>', views.video_edit, name='video_edit'),

]

MyTube/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

MyTube/app/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User



class Comment(models.Model):
    video = models.ForeignKey('studio.Video', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='comment_likes')
    dislikes = models.ManyToManyField(User, related_name='comment_dislikes')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)


    def count_replies(self):
        return Comment.objects.filter(parent=self).count()

MyTube/studio/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.contrib.auth.models import User

class Video(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='image/')
    file = models.FileField(upload_to='video/', validators=[FileExtensionValidator(allowed_extensions=['mp4'])])
    created_add = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='1')
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    dislikes = models.ManyToManyField(User, related_name='dislikes', blank=True)
    views = models.IntegerField(default=0)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return self.title

MyTube/studio/forms.py
from django import forms
from .bulma_mixin import BulmaMixin
from .models import Video


class VideoForm(BulmaMixin, forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Придумайте название к видео'}),
                            label='Название к видео')
    description = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Напишите описание к видео'}),
                                  label='Описание к видео')
    image = forms.ImageField(label='Загрузите обложку для видео')
    file = forms.FileField(label='Загрузите ваше видео')

    class Meta:
        model = Video
        fields = ['title', 'description', 'image', 'file']

MyTube/studio/views.py
from django.shortcuts import render, redirect
from .forms import *


def home(request):
    videos = Video.objects.all()
    confirm_delete = False
    action = request.GET.get('action')
    if action == 'delete':
        confirm_delete = True
    if request.GET.get('confirm'):
        Video.objects.get(pk=request.GET.get('pk')).delete()
        return redirect('studio:home')
    if action == 'archive':
        video = Video.objects.get(pk=request.GET.get('pk'))
        if video.archived:
            video.archived = False
        else:
            video.archived = True
        video.save()
    return render(request, 'home_studio.html', {'videos': videos, 'confirm_delete': confirm_delete})


def video_create(request):
    form = VideoForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        return redirect('studio:home')
    return render(request, 'video_create.html', {'form': form})


def video_edit(request, pk):
    video = Video.objects.get(pk=pk)
    form = VideoForm(request.POST or None, request.FILES or None, instance=video)
    if form.is_valid():
        form.save()
        return redirect('studio:home')
    return render(request, 'video_create.html', {'form': form})

MyTube/studio/templates/home_studio.html
{% extends 'layout.html' %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="title is-3">
                Контент на канале
            </div>
            <table class="table is-striped is-fullwidth is-hoverable">
                <thead>
                <tr>
                    <th>Видео</th>
                    <th>Дата</th>
                    <th>Просмотры</th>
                    <th>Комментарии</th>
                    <th>Нравится</th>
                    <th>Статус</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for video in videos %}
                    <div class="modal {% if confirm_delete %} is-active {% endif %}">
                        <div class="modal-background"></div>
                        <div class="modal-content">
                            <div class="box has-text-centered">
                                <div class="title is-3">Подтвердите удаление</div>
                                <a href="{% url 'studio:home' %}?confirm=True&pk={{ video.pk }}"
                                   class="button is-success">Подтвердить</a>
                                <a href="{% url 'studio:home' %}" class="button is-warning">Отмена</a>
                            </div>
                        </div>
                    </div>
                    <tr>
                        <td>
                            <a href="{% url 'app:video' video.pk %}">
                                <figure class="image is-128x128">
                                    <img src="{{ video.image.url }}" alt="">
                                </figure>
                            </a>
                        </td>
                        <td>{{ video.created_add }}</td>
                        <td>{{ video.views }} просмотров</td>
                        <td>{{ video.comment_set.count }} комментариев</td>
                        <td>{{ video.likes.count }}</td>
                        {% if video.archived %}
                            <td><span class="tag is-link">Архивировано</span></td>
                        {% else %}
                            <td><span class="tag is-link">Опубликовано</span></td>
                        {% endif %}
                        <td>
                            <div class="dropdown is-hoverable">
                                <div class="dropdown-trigger">
                                    <button class="button">Выберите действие</button>
                                </div>
                                <div class="dropdown-menu">
                                    <a href="{% url 'studio:video_edit' video.pk %}" class="dropdown-item">Изменить
                                        видео</a>
                                    <a href="{% url 'studio:home' %}?action=delete" class="dropdown-item">
                                        <ion-icon name="trash-outline"></ion-icon>
                                        Удалить
                                    </a>
                                    <a href="{% url 'studio:home' %}?action=archive&pk={{ video.pk }}"
                                       class="dropdown-item">
                                        {% if video.archived %}
                                            Вытащить из архива
                                        {% else %}
                                            Перенести в архив
                                        {% endif %}
                                    </a>
                                </div>
                            </div>

                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

MyTube/studio/templates/layout.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</head>
<body>
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'studio:home' %}">
            <i class="navbar-icon">
                <ion-icon name="logo-youtube"></ion-icon>
            </i>
            <span class="title is-4 ml-3">MyStudio</span>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <div class="navbar-item">
                <div class="field has-addons">
                    <div class="control">
                        <input class="input is-rounded" type="text" placeholder="Find a repository">
                    </div>
                    <div class="control">
                        <a class="button is-success is-rounded">
                            Search
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar-end">
            <div class="navbar-item has-dropdown is-hoverable">
                <div class="navbar-link">
                    <button class="button is-rounded">
                    </button>
                </div>
                <div class="navbar-dropdown">
                    <a href="" class="navbar-item">
                        Мой канал
                    </a>
                    <a href="{% url 'app:home' %}" class="navbar-item">
                        Главная
                    </a>
                    <a href="{% url 'users:sign_in' %}" class="navbar-item">
                        Сменить аккаунт
                    </a>
                    <a href="{% url 'users:sign_out' %}" class="navbar-item">
                        Выйти
                    </a>
                </div>
            </div>
            <a href="" class="navbar-item">
                <a href="{% url 'studio:video_create' %}" class="button">
                    <ion-icon name="videocam-outline"></ion-icon>
                    <span class="ml-2">
                        Создать
                    </span>
                </a>
            </a>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

MyTube/studio/templates/video_create.html
{% extends 'layout.html' %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-4">
                    <form method="post" class="box" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="field">
                                <label class="label">{{ field.label }}</label>
                                <div class="control">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                    <button class="button is-success">Загрузить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}