MyTube/MyTube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include(('app.urls', 'app'), namespace='app')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('studio/', include(('studio.urls', 'studio'), namespace='studio')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyTube/app/urls.py
from django . urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('video/<int:pk>', views.video, name='video'),
    path('likes/<int:pk>', views.likes, name='likes'),
    path('dislikes/<int:pk>', views.dislikes, name='dislikes'),
    path('comment_likes/<int:pk>', views.comment_likes, name='comment_likes'),
    path('comment_dislikes/<int:pk>', views.comment_dislikes, name='comment_dislikes'),
    path('reply/<int:pk>', views.reply, name='reply'),

]

MyTube/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

MyTube/app/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User



class Comment(models.Model):
    video = models.ForeignKey('studio.Video', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='comment_likes')
    dislikes = models.ManyToManyField(User, related_name='comment_dislikes')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)


    def count_replies(self):
        return Comment.objects.filter(parent=self).count()

MyTube/app/templates/base_layout.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</head>
<body>

<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'app:home' %}">
            <i class="navbar-icon">
                <ion-icon name="logo-youtube"></ion-icon>
            </i>
            <span class="title is-4 ml-3">MyTube</span>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <div class="navbar-item">
                <div class="field has-addons">
                    <div class="control">
                        <input class="input is-rounded" type="text" placeholder="Find a repository">
                    </div>
                    <div class="control">
                        <a class="button is-success is-rounded">
                            Search
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar-end">
            {% if not user.is_authenticated %}
                <div class="navbar-item">
                    <a class="button is-rounded" href="{% url 'users:sign_in' %}">
                        <ion-icon name="person-circle-outline" class="navbar-icon"></ion-icon>
                        <span class="subtitle is-5 ml-3">Войти</span>
                    </a>
                </div>
            {% else %}
                <div class="navbar-item has-dropdown is-hoverable mr-6">
                    <div class="navbar-link">
                        {{ user }}
                    </div>
                    <div class="navbar-dropdown">
                        <a href="{% url 'users:sign_out' %}" class="navbar-item has-text-danger">
                            Выйти
                        </a>
                        <a class="navbar-item" href="{% url 'studio:home' %}">
                            MyTube Studio
                        </a>
                    </div>

                </div>
            {% endif %}
        </div>
    </div>
</nav>
{% block content %}

{% endblock %}
</body>
</html>

MyTube/app/templates/error.html
{% extends 'base_layout.html' %}

{% block content %}

    <div class="section is-large">
        <div class="container">
            <div class="columns is-centered is-vcentered">
                <div class="column is-5">
                    <div class="notification has-text-centered">
                        <div class="title is-3">
                            Что-то пошло не так
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

MyTube/app/templates/home.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="columns">
        <div class="column is-2">
            <aside class="menu p-2">
                <ul class="menu-list">
                    <li>
                        <a>
                            <ion-icon name="home-outline"></ion-icon>
                            <span>Главная</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <ion-icon name="videocam-outline"></ion-icon>
                            <span>Shorts</span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <ion-icon name="list-outline"></ion-icon>
                            <span>Подписки</span>
                        </a>
                    </li>
                </ul>
                <hr>
                <ul class="menu-list">
                    <li>
                        <a>
                            <ion-icon name="list-circle-outline"></ion-icon>
                            <span>
                                Библиотека
                            </span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <ion-icon name="timer-outline"></ion-icon>
                            <span>
                                История
                            </span>
                        </a>
                    </li>
                </ul>
                <hr>
                <p class="menu-label">
                    Навигатор
                </p>
                <ul class="menu-list">
                    <li>
                        <a>
                            <ion-icon name="flame-outline"></ion-icon>
                            <span>
                                В тренде
                            </span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <ion-icon name="musical-notes-outline"></ion-icon>
                            <span>
                                Музыка
                            </span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <ion-icon name="film-outline"></ion-icon>
                            <span>
                                Фильмы
                            </span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <ion-icon name="radio-outline"></ion-icon>
                            <span>
                                Трансляции
                            </span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <ion-icon name="game-controller-outline"></ion-icon>
                            <span>
                                Видеоигры
                            </span>
                        </a>
                    </li>
                    <li>
                        <a>
                            <ion-icon name="american-football-outline"></ion-icon>
                            <span>
                                Спорт
                            </span>
                        </a>
                    </li>
                </ul>
            </aside>
        </div>
        <div class="column">
            <div class="columns is-multiline">
                {% for video in videos %}
                    <div class="column">
                        <a href="{% url 'app:video' video.pk %}">
                            <figure class="image video-image">
                                <img src="{{ video.image.url }}" alt="">
                            </figure>
                        </a>
                        <div class="content is-flex mt-3 is-align-items-center">
                            <div>
                                <figure class="image is-48x48">
                                    <img class="is-rounded" src="https://bulma.io/images/placeholders/48x48.png" alt="">
                                </figure>
                            </div>
                            <div class="content">
                                <div class="title is-4">{{ video.title }}</div>
                                <div class="subtitle">{{ video.author }}</div>
                                <div class="subtitle">
                                    <span>22 млн просмотров</span>
                                    <span>- {{ video.created_add }}</span>
                                </div>
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

MyTube/app/templates/replies.html
{% extends 'base_layout.html' %}

{% block content %}
    <section class="section">
        <div class="container">
            {% for comment in replies %}
                <div class="comment">
                    <div class="columns is-vcentered">
                        <div class="column is-1">
                            @{{ comment.user }}
                        </div>
                        <div class="column is-2">
                            {{ comment.date }}
                        </div>
                    </div>
                    <div class="content">
                        {{ comment.text }}
                    </div>
                    <div class="field has-addons">
                        <p class="control mx-2">
                            <a href="{% url 'app:comment_likes' comment.pk %}"
                               class="has-text-black {% if user in comment.likes.all %} has-text-success {% endif %}">
                                <ion-icon name="thumbs-up-outline"></ion-icon>
                            </a>
                            <span class="ml-2">{{ comment.likes.count }}</span>
                        </p>
                        <p class="control mx-2">
                            <a href="{% url 'app:comment_dislikes' comment.pk %}"
                               class="has-text-black {% if user in comment.dislikes.all %} has-text-danger {% endif %}">
                                <ion-icon name="thumbs-down-outline"></ion-icon>
                            </a>
                            <span class="ml-2">{{ comment.dislikes.count }}</span>
                        </p>
                        <p class="control">
                            <a href="{% url 'app:reply' comment.pk %}" class="ml-2 has-text-black">Ответить</a>
                        </p>
                    </div>
                    <div class="content has-text-info">
                        <ion-icon name="caret-down-outline"></ion-icon>
                        <a href="{% url 'app:reply' comment.pk %}?replies=True" class="ml-2">{{ comment.count_replies }}
                            ответов</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

MyTube/app/templates/reply.html
{% extends 'base_layout.html' %}

{% block content %}

    <div class="section is-large">
        <div class="container">
            <div class="columns is-centered is-vcentered">
                <div class="column is-5">
                    <div class="box">
                        <form method="post">
                            {% csrf_token %}
                            {{ form }}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

MyTube/app/templates/video.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <div class="column is-8">
                <video width="880" controls poster="{{ video.image.url }}" muted>
                    <source src="{{ video.file.url }}" type="video/mp4"/>
                </video>
                <div class="title mt-4">
                    {{ video }}
                </div>
                <div class="is-flex is-justify-content-space-between is-align-items-center">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-left">
                                <figure class="image is-48x48">
                                    <img class="is-rounded" src="https://bulma.io/images/placeholders/48x48.png" alt="">
                                </figure>
                            </div>
                            <div class="is-flex is-align-items-center">
                                <div class="media-content">
                                    <div class="title">{{ video.author }}</div>
                                    <div class="subtitle">22 mln views</div>
                                </div>
                                <button class="button ml-4 is-light has-text-dark is-medium is-rounded">
                                    Подписаться
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="is-flex">
                        <div class="field has-addons">
                            <p class="control">
                                <a href="{% url 'app:likes' video.pk %}"
                                   class="button is-dark {% if user in video.likes.all %} is-success {% endif %}">
                                    <ion-icon name="thumbs-up-outline"></ion-icon>
                                    <span class="content ml-4">
                                        {{ video.likes.count }}
                                    </span>
                                </a>
                            </p>
                            <p class="control">
                                <a href="{% url 'app:dislikes' video.pk %}"
                                   class="button is-dark {% if user in video.dislikes.all %} is-danger {% endif %}">
                                    <ion-icon name="thumbs-down-outline"></ion-icon>
                                    <span class="content ml-4">
                                        {{ video.dislikes.count }}
                                    </span>
                                </a>
                            </p>
                        </div>
                        <button class="button is-dark is-rounded">
                            <ion-icon name="share-outline"></ion-icon>
                            Поделиться
                        </button>
                        <button class="button is-dark is-rounded">
                            <ion-icon name="ellipsis-vertical-outline"></ion-icon>
                        </button>
                    </div>
                </div>
                <div class="columns is-vcentered">
                    <div class="column is-2">
                        <div class="title is-5">
                            20 comments
                        </div>
                    </div>
                    <div class="column is-3">
                        <div class="content is-flex is-justify-content-start is-align-items-center">
                            <ion-icon name="reorder-three-outline"></ion-icon>
                            <span class="subtitle ml-3">Упорядочить</span>
                        </div>
                    </div>
                </div>
                <div class="comments">
                    <form method="post" class="comment_form">
                        {% csrf_token %}
                        {{ form }}
                    </form>
                    <div class="comments_list">
                        {% for comment in video.comment_set.all %}
                            {% if comment.parent == None %}
                                <div class="comment">
                                    <div class="columns is-vcentered">
                                        <div class="column is-1">
                                            @{{ comment.user }}
                                        </div>
                                        <div class="column is-2">
                                            {{ comment.date }}
                                        </div>
                                    </div>
                                    <div class="content">
                                        {{ comment.text }}
                                    </div>
                                    <div class="field has-addons">
                                        <p class="control mx-2">
                                            <a href="{% url 'app:comment_likes' comment.pk %}"
                                               class="has-text-black {% if user in comment.likes.all %} has-text-success {% endif %}">
                                                <ion-icon name="thumbs-up-outline"></ion-icon>
                                            </a>
                                            <span class="ml-2">{{ comment.likes.count }}</span>
                                        </p>
                                        <p class="control mx-2">
                                            <a href="{% url 'app:comment_dislikes' comment.pk %}"
                                               class="has-text-black {% if user in comment.dislikes.all %} has-text-danger {% endif %}">
                                                <ion-icon name="thumbs-down-outline"></ion-icon>
                                            </a>
                                            <span class="ml-2">{{ comment.dislikes.count }}</span>
                                        </p>
                                        <p class="control">
                                            <a href="{% url 'app:reply' comment.pk %}" class="ml-2 has-text-black">Ответить</a>
                                        </p>
                                    </div>
                                    <div class="content has-text-info">
                                        <ion-icon name="caret-down-outline"></ion-icon>
                                        <a href="{% url 'app:reply' comment.pk %}?replies=True" class="ml-2">{{ comment.count_replies }} ответов</a>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="box">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt minus odit
                    suscipit?
                </div>
                <div class="box">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non officia voluptas
                    voluptate.
                </div>
                <div class="box">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic odit quo repellat.</div>
                <div class="box">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis provident quam
                    veritatis!
                </div>
                <div class="box">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad ducimus voluptates
                    voluptatum!
                </div>
            </div>
        </div>
    </div>
{% endblock %}